#!/bin/bash
query=$(printf "%s" "$*" | tr " " "+")
url=$(curl -s "https://rumble.com/search/video?q=$query" | grep -Eo "href=/[^>]*" | head -n 3 | tail -n1 | grep -Eo "/.*")
mpv "https://rumble.com$url"
