#!/bin/bash
results=$(curl -s "https://www.tiktok.com/discover/$1?lang=en" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0" | grep -Eo "/@[^@\"]+/video/[0-9]+" | head -n 1)
mpv "https://www.tiktok.com$results"
